/*
 * Wallaby.js - v1.0.869
 * https://wallabyjs.com
 * Copyright (c) 2014-2020 Wallaby.js - All Rights Reserved.
 *
 * This source code file is a part of Wallaby.js and is a proprietary (closed source) software.

 * IMPORTANT:
 * Wallaby.js is a tool made by software developers for software developers with passion and love for what we do.
 * Pirating the tool is not only illegal and just morally wrong,
 * it is also unfair to other fellow programmers who are using it legally,
 * and very harmful for the tool and its future.
 */
var tracer=global.$_$tracer;jasmine.ExceptionFormatter=function(){this.message=function(e){return e?e.name&&e.message?e.name+": "+e.message:e.toString():"empty error"},this.stack=function(e){return e?e.stack:null}},jasmine.SpyStrategy=function(e){e=e||{};var t=e.name||"unknown",n=e.fn||function(){},r=e.getSpy||function(){},i=function(){};this.identity=function(){return t},this.exec=function(){return i.apply(this,arguments)},this.callThrough=function(){return i=n,r()},this.returnValue=function(e){return i=function(){return e},r()},this.returnValues=function(){var e=Array.prototype.slice.call(arguments);return i=function(){return e.shift()},r()},this.throwError=function(e){return i=function(){throw e instanceof Error?e:new Error(e)},r()},this.callFake=function(e){return i=e,r()},this.stub=function(e){return i=function(){},r()}};var jasmineEnv=jasmine.getEnv(),currentSuite=[],originalDescribe=jasmineEnv.describe;jasmineEnv.describe=function(){currentSuite.push(arguments[0]);var e=Function.prototype.apply.call(originalDescribe,this,arguments);return currentSuite.pop(),e};var originalFDescribe=jasmineEnv.fdescribe;jasmineEnv.fdescribe=function(){currentSuite.push(arguments[0]);var e=Function.prototype.apply.call(originalFDescribe,this,arguments);return currentSuite.pop(),e};var existingSpecFilter=jasmineEnv.specFilter.bind(jasmineEnv),originalIt=jasmineEnv.it,originalFit=jasmineEnv.fit,overrideTestExecutionFunction=function(e){return function(){var t=arguments[1];{if("encountered a declaration exception"!==arguments[0]){if(!t)return Function.prototype.apply.call(e,this,arguments);t.length?arguments[1]=function(e){tracer.specSyncStart();try{var n=Function.prototype.apply.call(t,this,arguments)}finally{tracer.specSyncEnd()}return n}:arguments[1]=function(){tracer.specSyncStart();try{var e=Function.prototype.apply.call(t,this,arguments)}finally{tracer.specSyncEnd()}return e};var n=Function.prototype.apply.call(e,this,arguments);n.result&&(n.result._testFile=tracer.entryFile());var r=currentSuite.slice();return r.push(n.description),n.disabled=tracer.hasSpecFilter()&&!tracer.specFilter(r)&&existingSpecFilter(n.description),n}try{t()}catch(i){tracer.reportDeclarationError(i)}}}};jasmineEnv.it=overrideTestExecutionFunction(originalIt),jasmineEnv.fit=overrideTestExecutionFunction(originalFit);var originalAfterEach=jasmineEnv.afterEach;jasmineEnv.afterEach=function(){if(tracer.needToNotifySingleTestRun()){var e=arguments[0];e.length?arguments[0]=function(t){tracer.notifySingleTestAfterEach(function(){e(t)})}:arguments[0]=function(t){tracer.notifySingleTestAfterEach(function(){try{e()}finally{t()}})}}return Function.prototype.apply.call(originalAfterEach,this,arguments)},jasmineEnv.addReporter(tracer._jasmineAdapter),jasmineEnv.specFilter=function(){return!0};