/*
 * Wallaby.js - v1.0.869
 * https://wallabyjs.com
 * Copyright (c) 2014-2020 Wallaby.js - All Rights Reserved.
 *
 * This source code file is a part of Wallaby.js and is a proprietary (closed source) software.

 * IMPORTANT:
 * Wallaby.js is a tool made by software developers for software developers with passion and love for what we do.
 * Pirating the tool is not only illegal and just morally wrong,
 * it is also unfair to other fellow programmers who are using it legally,
 * and very harmful for the tool and its future.
 */
var Mocha;if(global.wallaby._testFrameworkPath)Mocha=require(global.wallaby._testFrameworkPath);else try{Mocha=require("mocha")}catch(e){Mocha=require("./framework/index.js")}var mocha,tracer=global.$_$tracer;tracer.start(function(){var e,t=tracer.initialSpecId(),n=[],r=global.$_$session,i=function(){return r!==global.$_$session};mocha.reporter(function(r){var o=r._grep||/.*/,s=r._invert,a=!1;if(r._invert=!1,r.runTest=function(e){if(!i()){var t=this.test,n=this;this.asyncOnly&&(t.asyncOnly=!0);try{t.on("error",function(e){n.fail(t,e)}),tracer.specSyncStart();try{t.run(e)}finally{tracer.specSyncEnd()}}catch(r){e(r)}}},r.grep=function(e,t){o=e,s=t,r._invert=!1},r.grepTotal=function(e){var t=0;return e.eachTest(function(e){var n=o.test(e.fullTitle());s&&(n=!n),n&&t++}),t},r._grep={test:function(e){var t=o.test(e);if(s&&(t=!t),!t)return!1;if(!tracer.hasSpecFilter())return!0;var r=n.slice(1);return r.push(e.substr(r.join(" ").length+(a&&0===r.length?0:1))),tracer.specFilter(r)}},tracer.needToNotifySingleTestRun()){var l=r.hook;r.hook=function(e,t){if(!i()){if("afterEach"!==e)return Function.prototype.apply.call(l,this,arguments);var n=arguments,o=this;tracer.notifySingleTestAfterEach(function(){Function.prototype.apply.call(l,o,n)}),r.hook=l}}}r.on("start",function(){i()||tracer.started({total:r.total})}),r.on("end",function(){i()||tracer.complete()}),r.on("suite",function(t){a=a||!!t.titlePath,i()||(n.push(t.title),e=t)}),r.on("suite end",function(){i()||n.pop()}),r.on("test",function(e){i()||(e._id=++t,e._failures=[],e._time=(new tracer._Date).getTime(),tracer.specStart(e._id,e.title))}),r.on("fail",function(e,t){i()||("hook"===e.type||e._finished?(e._hook="hook"===e.type&&e.title||!0,e._failures=[t],r.emit("test end",e)):e._failures.push(t))}),r.on("test end",function(e){if(!i()){e._finished=!0;var t=tracer.specEnd(),r=function(e){return!!e&&(e.pending===!0||r(e.parent))},o=r(e),s={id:e._id,timeRange:t,name:e.title,suite:n.slice(1),success:"passed"===e.state,skipped:o,time:o?0:(new tracer._Date).getTime()-e._time,log:[],hook:e._hook,slow:e.slow?e.duration>e.slow():void 0,testFile:e._testFile};if(!s.success&&!s.skipped)for(var a=e._failures,l=0;l<a.length;l++){var c=a[l];s.log.push(tracer.setAssertionData(c,{message:c.message,stack:c.stack}))}s.log.length||delete s.log,tracer.result(s)}})}),mocha.suite.on("pre-require",function(e){var t=e.it;e.it=function(){var e=Function.prototype.apply.call(t,this,arguments);return e._testFile=tracer.entryFile(),e},Object.keys(t).forEach(function(n){e.it[n]=t[n]})}),mocha.run(function(){})}),module.exports={init:function(e){mocha=new Mocha,mocha.files=e;try{mocha.slow&&mocha.slow(global.wallaby.slowTestThreshold),mocha.fullTrace&&mocha.fullTrace()}catch(t){}return mocha}};